version: 2
jobs:
  build:
    working_directory: /circleci-matrix
    docker:
    - image: docker.io/library/alpine:3.5
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apk add --no-cache bash ca-certificates ncurses wget
          wget -O bats-0.4.0.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
          tar -xzf bats-0.4.0.tar.gz
          cd bats-0.4.0
          ./install.sh /usr/local
    - run:
        name: Run tests
        command: bats tests/run.bats

